version: "2.3"

services:
  oms2:
    image: ${DOCKER_IMAGE}:${VERSION}
    environment:
      OMS2_ENV: dev
      OMS2_APISERVER_PORT: 8080
      OMS2_POSTGRES_DB_HOST: db
      OMS2_V7_ELASTIC_URL: http://esv701:9200/
      OMS2_APP_SERVICE_BASE_URL: http://127.0.0.1 # поменять после добавления wiremock
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_TYPE: remote
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_SERVICE_NAME: oms2
    stop_grace_period: 1m
    command: ["/wait-for-elastic.sh", "http://esv701:9200", "/usr/local/bin/oms2"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      db:
        condition: service_healthy
      esv701:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - oms2
#    logging:
#      entity: gelf
#      options:
#        gelf-address: udp://127.0.0.1:12201
    volumes:
      - ../../build/oms2:/usr/local/bin/oms2

  api:
    build:
      context: ../../.
      dockerfile: deployments/local/apidoc.Dockerfile
    command: ["caddy", "run", "--config", "/var/www/caddy.json"]
    ports:
      - "8765:80"
    volumes:
      - ../../api/openapi.yaml:/var/www/openapi.yaml
    networks:
      - oms2

  esv701:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - node.name=esv701
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9700:9200"
    networks:
      - oms2

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: 'oms2'
      POSTGRES_PASSWORD: 'oms2'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: ["CMD", "pg_isready" ,"-U", "oms2"]
      timeout: 5s
      retries: 10
    networks:
      - oms2

  liquibase:
    image: ${DOCKER_LIQUIBASE_IMAGE}:${VERSION}
    command: ["liquibase", "updateTestingRollback"]
    environment:
      LIQUIBASE_DATABASE: "oms2"
      LIQUIBASE_USERNAME: "oms2"
      LIQUIBASE_PASSWORD: "oms2"
      LIQUIBASE_CHANGELOG: "changelog.yaml"
      LIQUIBASE_DEBUG: "true"
      LIQUIBASE_URL: "jdbc:postgresql://db:5432/oms2"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - oms2

  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - oms2

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ../metrics/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always
    networks:
      - oms2

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ../metrics/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ../metrics/grafana/config.monitoring
    restart: always
    networks:
      - oms2

networks:
  oms2:
    driver: bridge
