version: '2'

networks:
  graylog.net:

volumes:
  graylog.data.elastic:
    driver: "local"
  graylog.data.mongo:
    driver: "local"

services:
  mongo:
    image: mongo:3
    hostname: mongo
    volumes:
      - graylog.data.mongo:/data/db
    networks:
      - graylog.net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    hostname: graylog.elastic
    environment:
      - http.host=0.0.0.0
      - transport.host=elasticsearch
      - network.host=0.0.0.0
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    networks:
      - graylog.net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - graylog.data.elastic:/usr/share/elasticsearch/data

  graylog:
    image: graylog2/server:2.3.2-2
    environment:
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=127.0.0.1
    ports:
      - 9000:9000
      - 12201:12201/udp
      - 12201:12201
      - 514:514/udp
    links:
      - mongo
      - elasticsearch
    networks:
      - graylog.net