version: "2.4"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: 'oms2'
      POSTGRES_PASSWORD: 'oms2'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: [ "CMD", "pg_isready" ,"-U", "oms2" ]
      timeout: 5s
      retries: 10
    networks:
      - oms2

  liquibase:
    image: ${DOCKER_LIQUIBASE_IMAGE}:${VERSION}
    command: [ "liquibase", "updateTestingRollback" ]
    environment:
      LIQUIBASE_DATABASE: "oms2"
      LIQUIBASE_USERNAME: "oms2"
      LIQUIBASE_PASSWORD: "oms2"
      LIQUIBASE_CHANGELOG: "changelog.yaml"
      LIQUIBASE_DEBUG: "true"
      LIQUIBASE_URL: "jdbc:postgresql://db:5432/oms2"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - oms2

networks:
  oms2:
    driver: bridge