{
 "title": "Business",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, route) (irate(oms2_duration_count[5m]))",
     "legendFormat": "RPS {{instance}} {{route}}"
    }
   ]
  },
  {
   "title": "Errors/Requests rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*sum by (instance, route) (irate(oms2_duration_count{success=\"error\"}[1m]))/sum by (instance, route) (irate(oms2_duration_count[1m]))",
     "legendFormat": "{{instance}} {{route}}"
    }
   ]
  },
  {
   "title": "Average Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(oms2_duration_sum{success=\"success\"}[5m])/irate(oms2_duration_count{success=\"success\"}[5m])",
     "legendFormat": "duration: {{instance}} {{route}}"
    }
   ]
  },
  {
   "title": "Duration (95th)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(oms2_duration_bucket{success=\"success\"}[5m])) by (le))",
     "legendFormat": "Success"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(oms2_duration_bucket{success=\"error\"}[5m])) by (le))",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}